Repository dlopp/question-box, pull requests merged in 2021-04, with the labels that each got.

#28 認証情報をCookieに保存する
  middleware/notAuthenticated.js
  nuxt.config.js
  package.json
  pages/admin/login.vue
  pages/admin/questions/_id.vue
  pages/admin/questions/index.vue
  store/index.js
  yarn.lock
Labels: enhancement

#30 Tailwindを拡張する
  tailwind.config.js
Labels: enhancement

#33 headerを作成した
  assets/images/header.png
  components/Layouts/Header.vue
  layouts/default.vue
Labels: markup

#35 twitterでシェアできるように
  assets/mixins/meta.js
  nuxt.config.js
  pages/answers/_id.vue
  pages/index.vue
Labels: enhancement

#37 ogp画像を追加
  nuxt.config.js
  pages/answers/_id.vue
Labels: enhancement

#39 QandAコンポーネント作成
  assets/images/answer.png
  assets/images/down.png
  assets/images/question.png
  assets/images/up.png
  components/Parts/QandA.vue
  layouts/default.vue
  pages/index.vue
  static/favicon.ico
  tailwind.config.js
Labels: enhancement

#34 FormとButtonの追加、tailwindのspacingを拡張
  components/Form.vue
  components/Parts/Button.vue
  components/README.md
  tailwind.config.js
Labels: markup

#42 Titleコンポーネント作成
  assets/images/form.png
  assets/images/qa.png
  components/Parts/QandA.vue
  components/Parts/Title.vue
  pages/index.vue
Labels: markup

#43 SNSコンポーネント作成
  assets/images/sns.png
  components/Logo.vue
  components/SNS.vue
  layouts/default.vue
  pages/index.vue
Labels: markup

#45 HeadLineコンポーネント作成とその他調整
  assets/images/hero2x.png
  components/Form.vue
  components/HeadLine.vue
  components/Layouts/Header.vue
  components/Parts/Button.vue
  components/Parts/QandA.vue
  components/Parts/Title.vue
  layouts/default.vue
  nuxt.config.js
  package.json
  pages/index.vue
  plugins/README.md
  plugins/vue-scrollto.js
  tailwind.config.js
  yarn.lock
Labels: enhancement, markup

#48 Shapeコンポーネント作成
  components/HeadLine.vue
  components/Parts/Title.vue
  components/SNS.vue
  components/Shapes/Bottom.vue
  components/Shapes/Middle.vue
  components/Shapes/Top.vue
  pages/index.vue
  tailwind.config.js
Labels: in progress, markup

#53 #49 管理者画面のUIをみやすくした
  pages/admin/questions/_id.vue
  pages/admin/questions/index.vue
Labels: markup

#60 回答詳細ページ作成
  components/Form.vue
  components/HeadLine.vue
  components/Layouts/Container.vue
  components/Parts/Button.vue
  components/Parts/Title.vue
  components/SNS.vue
  components/Shapes/Top.vue
  layouts/default.vue
  nuxt.config.js
  package.json
  pages/answers/_id.vue
  pages/index.vue
  plugins/vue-scrollto.js
  tailwind.config.js
  yarn.lock
Labels: enhancement

#62 titleとshapeの重なりを直した
  pages/index.vue
Labels: bug

#64 #51 Button.vueにホバーステートを追加した
  components/Form.vue
  components/Parts/Button.vue
  tailwind.config.js
Labels: markup

#66 QandAのアニメーション改善
  components/Parts/QandA.vue
  pages/index.vue
Labels: enhancement

#68 #63 errorページを追加＆bottomをstickyに
  layouts/default.vue
  layouts/error.vue
Labels: markup

#71 README書いた
  README.md
  static/screenshot.png
Labels: documentation

#83 #78 index.vueと一緒にした
  pages/answers/_id.vue
Labels: bug
